### ISSUE TITLE
add system test to verify juttle-engine binary works correctly

### ISSUE THREAD

**Issue by rlgomes** [juttle/juttle-engine#24]
when testing juttle-engine we're starting it up programatically and then interacting with it. This allows us to get correct coverage numbers and also shut it down cleanly. We need to also verify the bin/juttle-engine works as expected otherwise we'd leave ourselves open to some possible bugs.

**Comment by demmer** [comment]
Given the spate of npm issues we've had recently we should also have a verification test that makes sure the latest released binary works when installed via npm (both with and without -g).

**Comment by rlgomes** [comment]
@mstemm assigned to you and will take demmers comment to file another ticket for the npm stuff for myself.
