### ISSUE TITLE
can't run the juttle on Juttle Viewer

### ISSUE THREAD

**Issue by chenryn** [juttle/juttle-engine#93]
I got an error when I visit the juttle viewer page after install and run juttle-engine.

```
npm install -g juttle-engine
cp -r /opt/local/lib/node_modules/juttle-engine/examples .
juttle-engine &
open http://localhost:8080/?path=/examples/index.juttle
```

the webpage show me:

```
unexpected error
a.default.values(...).find is not a function
```

**Comment by rlgomes** [comment]
@chenryn what OS are you running on ? mac/linux ? also to help us diagnose a browser specific issue what browser and version are you using ?

**Comment by rlgomes** [comment]
@chenryn I invited you to our gitter chat channel as I can help figure out what is going on for the next hour (its 9pm here).

**Comment by chenryn** [comment]
Darwin MacBook-Pro 15.3.0
node v4.2.2
Chrome 42.0.2311.152 (64-bit)
